const currencyData = [
  {
    country: "United States",
    currency_code: "USD",
    currency_symbol: "$",
    flag: "./img/um.svg",
    currency_name: "UNITED STATES DOLLAR",
    rate: 1,
  },
  {
    country: "Afghanistan",
    currency_code: "AFN",
    currency_symbol: "؋",
    flag: "./img/af.svg",
    currency_name: "AFGHAN AFGHANI",
    rate: 90.09,
  },
  {
    country: "Albania",
    currency_code: "ALL",
    currency_symbol: "L",
    flag: "./img/al.svg",
    currency_name: "ALBANIAN LEK",
    rate: 106.45,
  },
  {
    country: "Algeria",
    currency_code: "DZD",
    currency_symbol: "دج",
    flag: "./img/dz.svg",
    currency_name: "ALGERIAN DINAR",
    rate: 136.56,
  },
  {
    country: "Andorra",
    currency_code: "EUR",
    currency_symbol: "€",
    flag: "./img/ad.svg",
    currency_name: "EURO",
    rate: 0.85,
  },
  {
    country: "Angola",
    currency_code: "AOA",
    currency_symbol: "Kz",
    flag: "./img/ao.svg",
    currency_name: "ANGOLAN KWANZA",
    rate: 630.5,
  },
  {
    country: "Argentina",
    currency_code: "ARS",
    currency_symbol: "$",
    flag: "./img/ar.svg",
    currency_name: "ARGENTINE PESO",
    rate: 99.75,
  },
  {
    country: "Pakistan",
    currency_code: "PKR",
    currency_symbol: "₨",
    flag: "./img/pk.svg",
    currency_name: "PAKISTANI RUPEE",
    rate: 160.5,
  },
];
